{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tienda-online.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    app: {{ .Values.backend.name }}
    tier: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.backend.name }}
    tier: backend
{{- end }}

