{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tienda-online.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    app: {{ .Values.database.name }}
    tier: database
spec:
  type: {{ .Values.database.service.type }}
  clusterIP: None  # Headless service para StatefulSet
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort }}
    protocol: TCP
    name: mysql
  selector:
    app: {{ .Values.database.name }}
    tier: database
{{- end }}

