{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tienda-online.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    app: {{ .Values.frontend.name }}
    tier: frontend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
      tier: frontend
  template:
    metadata:
      labels:
        {{- include "tienda-online.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app: {{ .Values.frontend.name }}
        tier: frontend
    spec:
      containers:
      - name: {{ .Values.frontend.name }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
          name: http
          protocol: TCP
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.frontend.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.frontend.readinessProbe | nindent 10 }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
{{- end }}

