apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mysql
    tier: database
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysql.rootPassword }}
  mysql-user: {{ .Values.secrets.mysql.user }}
  mysql-password: {{ .Values.secrets.mysql.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: backend
    tier: backend
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.backend.jwtSecret }}

